repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: trailing-whitespace
  - id: debug-statements
  - id: end-of-file-fixer
  - id: no-commit-to-branch
    args: [--branch, master, --branch, main]

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
    - id: python-use-type-annotations

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)

- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.0
  hooks:
    - id: pyupgrade

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
